# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- powershell: |
- task: PowerShell@2
  displayName: Run Tosca test(s) via ToscaCIClient
  inputs:
    targetType: 'filePath'
    #filePath: $(System.DefaultWorkingDirectory)\tests\run-tosca-test.ps1
    filePath: "C:/temp/AOS/tosca_execution_client.ps1"
    arguments: >
      -toscaServerUrl "http://192.168.222.132:5012/"
      -events '["3a02539f-f9e8-856c-4a85-6dc1060d65e3"]'
      -projectName "DEX_User"
      -creator "AOS API"
      -debug "true"
